---
version: '2'

services:

  web:
    image: bencord0/blog
    ports:
      - 80:8000
    links:
      - db
    environment:
      DEBUG: 1
      PORT: 8000
      ALLOWED_HOSTS: "*"
      DATABASE_URL: postgres://postgres:postgres@db/postgres

  importer:
    image: bencord0/blog
    links:
      - db
    volumes:
      - .:/blogposts
    entrypoint: [ "pipenv", "run" ]
    command: ["bash", "-c", "blog manage migrate; blog manage import_entries /blogposts;"]
    environment:
      DATABASE_URL: postgres://postgres:postgres@db/postgres

  db:
    image: postgres
    ports:
      - 5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
